version: '3.9'
services:
    login:
        build: josephgladwin/chatbotmini:latest
        ports:
          - "3000:3000"
        environment:
          - MONGODB_URL=mongodb+srv://mini:mini@mini.xpfnyj7.mongodb.net/
          - COMPOSE_PROJECT_NAME=chatbotLogin
    botactions:
        build: josephgladwin/miniactions:latest
        ports:
          - "5055:5055"
        depends_on:
          - database
        links:
          - database
    bot:
        build: josephgladwin/minibot:latest
        ports:
          - "5005:5005"
        depends_on:
          - botactions
        links:
          - botactions
    database:
        build: josephgladwin/mysqlchatbotmini:latest
        ports: 
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=student_data
        volumes: 
          - mysql-data:/var/lib/mysql

volumes:
  mysql-data: